language: python
python:
- "3.6"
install: pip install -r requirements.txt
sudo: false
env:
  global:
    secure: "S2zqA0OGW7zgJl2q3DOtuR/mY+DLDATs7hFqWY8mWSdlwiozW87JmzfDaoRHF0kyjo4meOPDfgQXZsfKuER5pvFVo8mY3tq3lEF7pCTPZmzlEOojSZlhsxzlCjs3++bZs4Y0uYDel+/9pZrUwVtvMaDEEO+pfl5xNavS1DVWWJCZvc+hiE6p5pdir/hGcPruQPTwZ2wXcMMRt0oldq5bAwrX14sJbUBdg1EP6oKJvl6/MVcgSnajJF/Ovkc9agUTURvvZDgCsgfLzBc9C/dx+w04/Ir2bH867C7AZYxT3YjunRVsId5KWL7lDaP1kbogQH7JMSIioxmlWVN3OWKImWo+UgK4vr5qiNZdIlE4yZUaBUD1wXuCaZ78Pks9uRwlf0ElKZZ8tZ0wwWMQZJ3QxEDomAPBlmj2oqed7WdCm4gnpfjqq8P2pap9Wm1uEITskaFWQSNd+eZ2ar3tLlbh7aSqyWsX3ojSBwBF+P4+sNxPUIpzi6QFUZBZD9G4mu71a/YB7lhpV2z+SMgITE+hFmw5bj19TxAfbnVz1FJdJgDmYXG4mDTFhTLzFo59j62I0gW0yQmSisBkT8vTHAwAySPmPYNNI7hqEsAs6zFTBcK27SKc3XJANn5Mv0KkrDaXuMeliUec/98l40rLu/Uar8VBQlM7cqReimO66zRpn+0="
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
