language: python
python:
  - "3.6"
install:
  pip install -r requirements.txt
sudo: false
env:
  global:
  - secure: lOF1kbwQBkS3IcTQAUv21FvwDzuOgM/CtmWWxCHW//D/zAChs0rVQCKy33HxYJC58t9tPZHpRhq16VAhlKwYFPTjJTwbUefQkiz1gRXQ+PrFaJLjlu0fr8N0ArrNKEbWzBfowkhQB/YdTWNPacVAauG7BgKzPYc8+SakYNDWR1mjEBNfynAXAG0bBorDG3eomPCzPAfHJuay4EyS0iohzV5ug8/j5GNDdO45v95oWc+Oj1+UY6m4QfSFwB19iWtcbCAE2fSzgMP5mpc9YI6vwFQEDPm94ukeG9ObdVStz+gf0m8uNMLOvns13TSHBx5qlQfpRH19PxtNBJuK8R9R63jLD/yatSEJNpnmSPi4qT5p8aK/5DAFsV9BSs13dysufmhXgF/B/wnkFuLg11iwD9zxn4o9/l4lOfclPmOD0+4WfIvxHzjUAh6UCliAmGv4p6+7un7alK/j+n2XhObeJz4lknB4dhFjg2TQ0kjbjDB9zthDHrv51IVyoQSwyB/Pllq38dOop7shI/97Mr3+S1q8pZMHEAzYPOeTizni61F5bTVni4h47LMTLnQx7Yo4a0F+9fqhn64b7BwDx53viJUTdERMt3TKEvZ7V2oFPq4vz+ydFSbLA7+wqCThJOGdGQHOvZBET1yaWiAdkEZdGwGNDZ55kkQ6pHuJCwVv7oI=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
