language: python
python:
- "3.6"
install: pip install -r requirements.txt
sudo: false
env:
  global:
  - secure: uXXwVYQI3t//Z9BGr1mAwexi+iVDUW4CpazXagdu83yWmSvJoOZQQHUK+0H4pmRCW+k+W4yfODvazKYZkVr6q/33qogNGlofJ8jScTVKSlC7goDICBzC9FKLkmpegJRraHXmGyV7r9EpvLxy4vIcwESgWZrvmjKpUb5OCrrLBrjvCLYhrquJHVy4pDqbbrv8VR39VgOamOSwqNcNzvtnD5k6Xh8ne+/4eHtyYb8NLaG06tOBODEKSFXGgoqlv+vIi2qrJrQ3vUS3xOAoZqFh+O/OX4Tn3RCioJv5/RoQsgqNfdccSu1axpy7fwxtgON/ImcYqXbgyIW/PNaMlPXQxXbv6uyDI+TgQxT9DCn5aFA8wm5FHVpmMuo4bOWVO7CQgBZKQ9Xbk7B+olfajFNOv+wAZsDUMXa5LhecKBM4vOlC2cJlRQUrXxORPO64AIF2UFkpOnJoukuGcB4jriYUSLfK74dvRB+cpxbVZAjbOFW2sQOBsYgNyMmoLBpPYeLDPncLKmSQWGmuMmliLXrGb6OeHM9mbUnEtQYsvzgDwHWkQgYs8mLl+dgCl1ScgTWL1NunvpddVphAUF+VDIlU2EuvahZR0O6Udd+YKDStUOg5DW31ktRZ25t+M025Wr7jm2+buTSUC2RrfIoqR8036ZvDmsQdLRZ+Vig78U6cOkw=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
